[package]
name = "naho_data_receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
exitcode = "1.1.2"
log = "0.4.22"
log4rs = "1.3.0"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.135"
serialport = "=4.6.1"
sqlite = "0.36.1"
